### ISSUE TITLE
Problem in installing the plugin some thing went wrong with gps

### ISSUE THREAD

**Issue by jounayd** [MobileChromeApps/google-play-services#16]
When i try to install the plugin I have a google play services error:

<code>D:\WS\phonegap\IMCWS\imc>phonegap plugin add com.google.cordova.admob

Fetching plugin "com.google.cordova.admob" via plugin registry

Installing "com.google.cordova.admob" for android

Fetching plugin "https://github.com/floatinghotpot/google-play-services" via git
 clone

Failed to install 'com.google.cordova.admob':Error: Command failed: C:\Windows\s
ystem32\cmd.exe /s /c "git clone "https://github.com/floatinghotpot/google-play-
services" "C:\Users\DELL\AppData\Local\Temp\plugman\git\1424519374939""
fatal: could not create work tree dir 'C:\Users\DELL\AppData\Local\Temp\plugman\
git\1424519374939'.: No such file or directory

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)

Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git clone "https://git
hub.com/floatinghotpot/google-play-services" "C:\Users\DELL\AppData\Local\Temp\p
lugman\git\1424519374939""
fatal: could not create work tree dir 'C:\Users\DELL\AppData\Local\Temp\plugman\
git\1424519374939'.: No such file or directory

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)</code>

**Comment by jounayd** [comment]
Sorry a mistake
